name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build release binaries
      run: make release VERSION=${{ steps.version.outputs.VERSION }}
    
    - name: Calculate checksums
      id: checksums
      run: |
        SHA256_AMD64=$(shasum -a 256 mcli-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz | cut -d' ' -f1)
        SHA256_ARM64=$(shasum -a 256 mcli-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz | cut -d' ' -f1)
        echo "SHA256_AMD64=$SHA256_AMD64" >> $GITHUB_OUTPUT
        echo "SHA256_ARM64=$SHA256_ARM64" >> $GITHUB_OUTPUT
    
    - name: Generate Homebrew formula
      id: homebrew
      run: |
        cat > homebrew-formula.rb << EOF
        class Mcli < Formula
          desc "LeanMCP CLI - Manage projects and chats"
          homepage "https://github.com/rosaboyle/leanmcp-cli-chat-deploy"
          version "${{ steps.version.outputs.VERSION }}"

          if OS.mac? && Hardware::CPU.arm?
            url "https://github.com/rosaboyle/leanmcp-cli-chat-deploy/releases/download/v${{ steps.version.outputs.VERSION }}/mcli-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz"
            sha256 "${{ steps.checksums.outputs.SHA256_ARM64 }}"
          elsif OS.mac? && Hardware::CPU.intel?
            url "https://github.com/rosaboyle/leanmcp-cli-chat-deploy/releases/download/v${{ steps.version.outputs.VERSION }}/mcli-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz"
            sha256 "${{ steps.checksums.outputs.SHA256_AMD64 }}"
          end

          def install
            bin.install "mcli-darwin-arm64" => "mcli" if OS.mac? && Hardware::CPU.arm?
            bin.install "mcli-darwin-amd64" => "mcli" if OS.mac? && Hardware::CPU.intel?
          end

          test do
            system "#{bin}/mcli", "version"
          end
        end
        EOF
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mcli-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz
          mcli-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz
        body: |
          ## MCLI v${{ steps.version.outputs.VERSION }}
          
          🚀 **Installation via Homebrew:**
          ```bash
          brew tap rosaboyle/mcli
          brew install mcli
          ```
          
          📦 **Manual Download:**
          - macOS Intel: mcli-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz
          - macOS Apple Silicon: mcli-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz
          
          🍺 **Homebrew Formula (for tap repository):**
          ```ruby
          $(cat homebrew-formula.rb)
          ```
          
          **Checksums:**
          - AMD64: ${{ steps.checksums.outputs.SHA256_AMD64 }}
          - ARM64: ${{ steps.checksums.outputs.SHA256_ARM64 }}
        generate_release_notes: true
